#!/bin/bash

mkdir -p $HOME/.zsh
if [ ! -e $HOME/.zsh/ohmyzsh ]; then
  git clone --depth=1 https://github.com/ohmyzsh/ohmyzsh.git $HOME/.zsh/ohmyzsh
fi

mkdir -p $HOME/.vim/bundle
if [ ! -e $HOME/.vim/bundle/Vundle.vim ]; then
  git clone https://github.com/VundleVim/Vundle.vim.git $HOME/.vim/bundle/Vundle.vim
fi

if [[ "$(uname)" == "Darwin" ]]; then
  if [ ! -e /opt/homebrew/bin/brew ]; then
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  fi
  /opt/homebrew/bin/brew bundle -v
fi
