# *> ~/.zshrc


ZSH=$HOME/.zsh/ohmyzsh
ZSH_CUSTOM=$HOME/.zsh/themes
ZSH_THEME="workspace"
ZSH_DISABLE_COMPFIX="true"
ZSH_COMPDUMP=$ZSH/cache/.zcompdump-$HOST
DISABLE_AUTO_UPDATE="true"
HYPHEN_INSENSITIVE="true"
PROMPT_EOL_MARK=''

plugins=(git python pip virtualenv)
source $ZSH/oh-my-zsh.sh
export EDITOR=vim

if [ -e "/opt/homebrew" ]; then
  export PATH="/opt/homebrew/bin:$PATH"
  export PATH="/opt/homebrew/opt/coreutils/libexec/gnubin:$PATH"
  export PATH="/opt/homebrew/opt/binutils/bin:$PATH"
  export PATH="/opt/homebrew/opt/bzip2/bin:$PATH"
  export PATH="/opt/homebrew/opt/gnu-sed/libexec/gnubin:$PATH"
fi

[ -e "$HOME/Tools" ] && export PATH="$HOME/Tools:$PATH"
[ -e "$HOME/.opencode" ] && export PATH="$HOME/.opencode/bin:$PATH"
[ -e "/opt/homebrew/opt/ruby/bin" ] && export PATH="/opt/homebrew/opt/ruby/bin:$PATH"
[ -e "$HOME/.asdf" ] && export PATH="${ASDF_DATA_DIR:-$HOME/.asdf}/shims:$PATH"

for f in $(find ~/.zsh/plugins/ -maxdepth 1 -type f -name '*.zsh'); do
  source $f;
done

command -v keychain > /dev/null && keychain -q ~/.ssh/id_ed25519
