if [ -e "/opt/homebrew" ]; then
  export PATH="/opt/homebrew/bin:$PATH"
  export PATH="/opt/homebrew/opt/coreutils/libexec/gnubin:$PATH"
  export PATH="/opt/homebrew/opt/binutils/bin:$PATH"
  export PATH="/opt/homebrew/opt/bzip2/bin:$PATH"
fi
export PATH="$HOME/Tools:$PATH"
export EDITOR=vim

alias t='terraform'
alias tf='terraform'

plugins=(git scala python pip virtualenv)

ZSH=$HOME/.zsh/ohmyzsh
ZSH_CUSTOM=$HOME/.zsh/themes
ZSH_THEME="workspace"
DISABLE_AUTO_UPDATE="true"
HYPHEN_INSENSITIVE="true"
ZSH_DISABLE_COMPFIX="true"
PROMPT_EOL_MARK=''

for f in $(find ~/.zsh/plugins/ -maxdepth 1 -type f -name '*.zsh'); do
  source $f;
done

export PYENV_ROOT="$HOME/.pyenv"
[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"

if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
  eval "$(pyenv virtualenv-init -)"
fi

[ -d "/opt/homebrew/opt/ruby/bin" ] && export PATH="/opt/homebrew/opt/ruby/bin:$PATH"
[ -d "$HOME/.asdf" ] && export PATH="${ASDF_DATA_DIR:-$HOME/.asdf}/shims:$PATH"

